spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ru.IrinaTik.diploma.util.MySQLCustomDialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
  sql:
    init:
      mode: never

logging:
  file:
    name: logs\SearchEngineInfo.log

config:
  sitelist:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: http://www.playback.ru
      name: Playback
    - url: https://ipfran.ru
      name: Институт прикладной физики РАН
  useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 YaBrowser/21.9.0.1044 Yowser/2.5 Safari/537.36
  referrer: http://www.google.com